<?php
return array(
  'keys' => '定義項目',
  'schedule_method' => '定期カレンダー反映方法',
  'lesson' => 'レッスン',
  'english_talk_lesson' => '英会話レッスン',
  'kids_lesson' => '習い事',
  'course_minutes' => '授業時間',
  'course_type' => '授業形式',
  'charge_grade' => '担当学年',
  'charge_subject' => '担当科目',
  'charge_subject_level' => '担当科目Lv',
  'course' => 'コース',
  'grade' => '学年',
  'level' => '難易度',
  'place' => '場所',
  'absence_type' => '休み種別',
  'grade_adj' => '学年調整値(留年など)',
  'student_type' => '生徒種別',
  'comment_type' => 'コメント種別',
  'milestone_type' => '目標種別',
  'howto' => '当塾をお知りになった方法は何でしょうか',
  'lesson_place' => '希望校舎',
  'lesson_place_floor' => '校舎フロア',
  'lesson_subject' => 'レッスン希望科目',
  'lesson_subject_level' => '科目希望対応',
  'lesson_week' => 'レッスン可能曜日',
  'lesson_time' => 'レッスン可能時間',
  'work_time' => '勤務可能時間',
  'english_teacher' => '英会話講師希望',
  'piano_level' => 'ピアノ経験',
  'matching_decide' => 'マッチング決定理由',
  'teacher_character' => '講師特性',
  'student_character' => '生徒特性',
);
?>
