<?php

use Illuminate\Database\Seeder;
use App\Models\Curriculum;

class CurriculumTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $datam  = [
          ['curriculum' => [ 'name' => '正負の数','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '加法　減法','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '乗法　除法','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '四則の計算','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '文字式の計算','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '関数','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '比例　反比例','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '比例のグラフ','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '反比例のグラフ','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '等式の変形','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '文字式の利用','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '乗法公式','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '因数分解','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => 'ルートの計算','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '一次方程式','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '連立方程式','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '二次方程式','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '確率','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '資料の活用','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '円と角度','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '作図','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '文字式の証明','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '一次関数','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '一次関数のグラフ','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '変化の割合','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '二次関数','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '二次関数のグラフ','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '関数と方程式','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '平面図形の角','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '三角形の合同','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '合同の証明','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '三角形の相似','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '相似の証明','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '三平方の定理','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '平面図形の面積','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '空間図形の体積','create_user_id' => 1 ],'subject_id' => 7],
          ['curriculum' => [ 'name' => '植物','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '動物','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '細胞　遺伝','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '自然環境','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '大地','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '天気','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '天体','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '物質','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '光　音','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '力','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '運動','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => 'エネルギー','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '電気','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '化学変化','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => 'イオン','create_user_id' => 1 ],'subject_id' => 9],
          ['curriculum' => [ 'name' => '漢字　語句','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '作文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '発表文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '報告文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '記録文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '案内文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '小説','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '随筆','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '論説文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '古文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '漢文','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '文　文節　単語','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '自立語　付属語','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '動詞　形容詞　名詞','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '助詞　助動詞','create_user_id' => 1 ],'subject_id' => 6],
          ['curriculum' => [ 'name' => '式の計算　実数','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '１次不等式','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '集合　命題','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '２次関数','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '２次不等式','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '三角比','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => 'データの分析','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '場合の数　確率','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '図形の性質','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '整数の性質','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => 'ユークリッドの互除法','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '１次不定方程式','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => 'ｎ 進法','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '式と証明','create_user_id' => 1 ],'subject_id' => 15],
          ['curriculum' => [ 'name' => '複素数','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '高次方程式','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '直線・円の方程式','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '軌跡　領域','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '三角関数','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '指数関数','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '対数関数','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '微分法','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '積分法','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => 'ベクトル','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '数列','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '確率分布','create_user_id' => 1 ],'subject_id' => 16],
          ['curriculum' => [ 'name' => '複素数平面','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '２次曲線','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '媒介変数','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '極座標　極方程式','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '分数関数','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '無理関数','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '数列の極限','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '関数の極限','create_user_id' => 1 ],'subject_id' => 17],
          ['curriculum' => [ 'name' => '運動','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '力学','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '熱力学','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '波動','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '電磁気','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => 'コンデンサー','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '交流回路','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => '量子力学','create_user_id' => 1 ],'subject_id' => 19],
          ['curriculum' => [ 'name' => 'mol 計算','create_user_id' => 1 ],'subject_id' => 20],
          ['curriculum' => [ 'name' => '溶解度','create_user_id' => 1 ],'subject_id' => 20],
          ['curriculum' => [ 'name' => '電気分解','create_user_id' => 1 ],'subject_id' => 20],
          ['curriculum' => [ 'name' => '反応速度','create_user_id' => 1 ],'subject_id' => 20],
          ['curriculum' => [ 'name' => '化学平衡','create_user_id' => 1 ],'subject_id' => 20],

        ];

        foreach($datam as $data){
          $item = Curriculum::create($data['curriculum']);
          $item->subjects()->attach($data['subject_id']);
        }
    }
}
