<?php  return array(	"announcement_type" => [
		"nitification" => [
			"attribute_value" => "nitification",
			"attribute_name" => "お知らせ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"importance" => [
			"attribute_value" => "importance",
			"attribute_name" => "重要",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
	],
	"bank_account_type" => [
		"normal" => [
			"attribute_value" => "normal",
			"attribute_name" => "普通",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"current" => [
			"attribute_value" => "current",
			"attribute_name" => "当座",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"savings" => [
			"attribute_value" => "savings",
			"attribute_name" => "貯蓄",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
	],
	"calendar_status" => [
		"dummy" => [
			"attribute_value" => "dummy",
			"attribute_name" => "ダミー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"new" => [
			"attribute_value" => "new",
			"attribute_name" => "予定(下書き)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"confirm" => [
			"attribute_value" => "confirm",
			"attribute_name" => "予定確認中",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"fix" => [
			"attribute_value" => "fix",
			"attribute_name" => "授業予定",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"presence" => [
			"attribute_value" => "presence",
			"attribute_name" => "出席済み",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"absence" => [
			"attribute_value" => "absence",
			"attribute_name" => "欠席",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"rest" => [
			"attribute_value" => "rest",
			"attribute_name" => "休み",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"rest_cancel" => [
			"attribute_value" => "rest_cancel",
			"attribute_name" => "休み取消(確認待ち)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"lecture_cancel" => [
			"attribute_value" => "lecture_cancel",
			"attribute_name" => "休み",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"cancel" => [
			"attribute_value" => "cancel",
			"attribute_name" => "キャンセル",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
	],
	"charge_grade" => [
		"k" => [
			"attribute_value" => "k",
			"attribute_name" => "幼稚園",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"e" => [
			"attribute_value" => "e",
			"attribute_name" => "小学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"j" => [
			"attribute_value" => "j",
			"attribute_name" => "中学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"h" => [
			"attribute_value" => "h",
			"attribute_name" => "高校",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"o" => [
			"attribute_value" => "o",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"charge_subject" => [
		"e_japanese" => [
			"attribute_value" => "e_japanese",
			"attribute_name" => "国語(小学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "e",
			"sort_no" => "1",
		],
		"j_japanese" => [
			"attribute_value" => "j_japanese",
			"attribute_name" => "国語(中学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "j",
			"sort_no" => "1",
		],
		"contemporary_japanese" => [
			"attribute_value" => "contemporary_japanese",
			"attribute_name" => "現代文",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "1",
		],
		"e_math" => [
			"attribute_value" => "e_math",
			"attribute_name" => "算数(小学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "e",
			"sort_no" => "2",
		],
		"j_math" => [
			"attribute_value" => "j_math",
			"attribute_name" => "数学(中学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "j",
			"sort_no" => "2",
		],
		"classical_japanese" => [
			"attribute_value" => "classical_japanese",
			"attribute_name" => "古文",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "2",
		],
		"e_english" => [
			"attribute_value" => "e_english",
			"attribute_name" => "英語(小学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "e",
			"sort_no" => "3",
		],
		"j_english" => [
			"attribute_value" => "j_english",
			"attribute_name" => "英語(中学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "j",
			"sort_no" => "3",
		],
		"classical_chinese" => [
			"attribute_value" => "classical_chinese",
			"attribute_name" => "漢文",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "3",
		],
		"e_science" => [
			"attribute_value" => "e_science",
			"attribute_name" => "理科(小学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "e",
			"sort_no" => "4",
		],
		"j_science" => [
			"attribute_value" => "j_science",
			"attribute_name" => "理科(中学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "j",
			"sort_no" => "4",
		],
		"essay" => [
			"attribute_value" => "essay",
			"attribute_name" => "小論文",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "4",
		],
		"e_society" => [
			"attribute_value" => "e_society",
			"attribute_name" => "社会(小学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "e",
			"sort_no" => "5",
		],
		"j_society" => [
			"attribute_value" => "j_society",
			"attribute_name" => "社会(中学)",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "j",
			"sort_no" => "5",
		],
		"math1" => [
			"attribute_value" => "math1",
			"attribute_name" => "数ⅠA",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "5",
		],
		"math2" => [
			"attribute_value" => "math2",
			"attribute_name" => "数ⅡB",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "6",
		],
		"math3" => [
			"attribute_value" => "math3",
			"attribute_name" => "数Ⅲ",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "7",
		],
		"english1" => [
			"attribute_value" => "english1",
			"attribute_name" => "英語",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "8",
		],
		"phisics" => [
			"attribute_value" => "phisics",
			"attribute_name" => "物理",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "9",
		],
		"chemistry" => [
			"attribute_value" => "chemistry",
			"attribute_name" => "化学",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "10",
		],
		"biology" => [
			"attribute_value" => "biology",
			"attribute_name" => "生物",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "11",
		],
		"world_history" => [
			"attribute_value" => "world_history",
			"attribute_name" => "世界史",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "12",
		],
		"japanese_history" => [
			"attribute_value" => "japanese_history",
			"attribute_name" => "日本史",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "13",
		],
		"geography" => [
			"attribute_value" => "geography",
			"attribute_name" => "地理",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "14",
		],
		"political_economy" => [
			"attribute_value" => "political_economy",
			"attribute_name" => "政治経済",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "15",
		],
		"contemporary_history" => [
			"attribute_value" => "contemporary_history",
			"attribute_name" => "現代社会",
			"parent_attribute_key" => "charge_grade",
			"parent_attribute_value" => "h",
			"sort_no" => "16",
		],
	],
	"charge_subject_level" => [
		"1" => [
			"attribute_value" => "1",
			"attribute_name" => "担当不可",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"10" => [
			"attribute_value" => "10",
			"attribute_name" => "補習可",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"20" => [
			"attribute_value" => "20",
			"attribute_name" => "受験対応可",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"30" => [
			"attribute_value" => "30",
			"attribute_name" => "難関対応可",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
	],
	"charge_subject_level_item" => [
		"e_japanese_level" => [
			"attribute_value" => "e_japanese_level",
			"attribute_name" => "国語(小学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "e_japanese",
			"sort_no" => "1",
		],
		"j_japanese_level" => [
			"attribute_value" => "j_japanese_level",
			"attribute_name" => "国語(中学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "j_japanese",
			"sort_no" => "1",
		],
		"contemporary_japanese_level" => [
			"attribute_value" => "contemporary_japanese_level",
			"attribute_name" => "現代文(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "contemporary_japanese",
			"sort_no" => "1",
		],
		"e_math_level" => [
			"attribute_value" => "e_math_level",
			"attribute_name" => "算数(小学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "e_math",
			"sort_no" => "2",
		],
		"j_math_level" => [
			"attribute_value" => "j_math_level",
			"attribute_name" => "数学(中学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "j_math",
			"sort_no" => "2",
		],
		"classical_japanese_level" => [
			"attribute_value" => "classical_japanese_level",
			"attribute_name" => "古文(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "classical_japanese",
			"sort_no" => "2",
		],
		"e_english_level" => [
			"attribute_value" => "e_english_level",
			"attribute_name" => "英語(小学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "e_english",
			"sort_no" => "3",
		],
		"j_english_level" => [
			"attribute_value" => "j_english_level",
			"attribute_name" => "英語(中学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "j_english",
			"sort_no" => "3",
		],
		"classical_chinese_level" => [
			"attribute_value" => "classical_chinese_level",
			"attribute_name" => "漢文(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "classical_chinese",
			"sort_no" => "3",
		],
		"e_science_level" => [
			"attribute_value" => "e_science_level",
			"attribute_name" => "理科(小学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "e_science",
			"sort_no" => "4",
		],
		"j_science_level" => [
			"attribute_value" => "j_science_level",
			"attribute_name" => "理科(中学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "j_science",
			"sort_no" => "4",
		],
		"essay_level" => [
			"attribute_value" => "essay_level",
			"attribute_name" => "小論文(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "essay",
			"sort_no" => "4",
		],
		"e_society_level" => [
			"attribute_value" => "e_society_level",
			"attribute_name" => "社会(小学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "e_society",
			"sort_no" => "5",
		],
		"j_society_level" => [
			"attribute_value" => "j_society_level",
			"attribute_name" => "社会(中学)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "j_society",
			"sort_no" => "5",
		],
		"math1_level" => [
			"attribute_value" => "math1_level",
			"attribute_name" => "数ⅠA(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "math1",
			"sort_no" => "5",
		],
		"math2_level" => [
			"attribute_value" => "math2_level",
			"attribute_name" => "数ⅡB(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "math2",
			"sort_no" => "6",
		],
		"math3_level" => [
			"attribute_value" => "math3_level",
			"attribute_name" => "数Ⅲ(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "math3",
			"sort_no" => "7",
		],
		"english1_level" => [
			"attribute_value" => "english1_level",
			"attribute_name" => "英語(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "english1",
			"sort_no" => "8",
		],
		"phisics_level" => [
			"attribute_value" => "phisics_level",
			"attribute_name" => "物理(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "phisics",
			"sort_no" => "9",
		],
		"chemistry_level" => [
			"attribute_value" => "chemistry_level",
			"attribute_name" => "化学(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "chemistry",
			"sort_no" => "10",
		],
		"biology_level" => [
			"attribute_value" => "biology_level",
			"attribute_name" => "生物(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "biology",
			"sort_no" => "11",
		],
		"world_history_level" => [
			"attribute_value" => "world_history_level",
			"attribute_name" => "世界史(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "world_history",
			"sort_no" => "12",
		],
		"japanese_history_level" => [
			"attribute_value" => "japanese_history_level",
			"attribute_name" => "日本史(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "japanese_history",
			"sort_no" => "13",
		],
		"geography_level" => [
			"attribute_value" => "geography_level",
			"attribute_name" => "地理(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "geography",
			"sort_no" => "14",
		],
		"political_economy_level" => [
			"attribute_value" => "political_economy_level",
			"attribute_name" => "政治経済(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "political_economy",
			"sort_no" => "15",
		],
		"contemporary_history_level" => [
			"attribute_value" => "contemporary_history_level",
			"attribute_name" => "現代社会(高校)",
			"parent_attribute_key" => "charge_subject",
			"parent_attribute_value" => "contemporary_history",
			"sort_no" => "16",
		],
	],
	"comment_type" => [
		"promotion" => [
			"attribute_value" => "promotion",
			"attribute_name" => "進学、進級に関して",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"examination" => [
			"attribute_value" => "examination",
			"attribute_name" => "試験に関して",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"study" => [
			"attribute_value" => "study",
			"attribute_name" => "学習に関して",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"other" => [
			"attribute_value" => "other",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
	],
	"course" => [
		"1" => [
			"attribute_value" => "1",
			"attribute_name" => "マンツーマン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"2" => [
			"attribute_value" => "2",
			"attribute_name" => "グループ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"3" => [
			"attribute_value" => "3",
			"attribute_name" => "ファミリー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"4" => [
			"attribute_value" => "4",
			"attribute_name" => "夏期講習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"5" => [
			"attribute_value" => "5",
			"attribute_name" => "冬期講習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"6" => [
			"attribute_value" => "6",
			"attribute_name" => "春期講習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"7" => [
			"attribute_value" => "7",
			"attribute_name" => "南多摩4年コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"8" => [
			"attribute_value" => "8",
			"attribute_name" => "ビジネス英会話グループ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
	],
	"course_minutes" => [
		"30" => [
			"attribute_value" => "30",
			"attribute_name" => "３０分",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"40" => [
			"attribute_value" => "40",
			"attribute_name" => "４０分",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"60" => [
			"attribute_value" => "60",
			"attribute_name" => "６０分",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"90" => [
			"attribute_value" => "90",
			"attribute_name" => "９０分",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"120" => [
			"attribute_value" => "120",
			"attribute_name" => "１２０分",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"course_type" => [
		"single" => [
			"attribute_value" => "single",
			"attribute_name" => "マンツーマン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"group" => [
			"attribute_value" => "group",
			"attribute_name" => "グループ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"family" => [
			"attribute_value" => "family",
			"attribute_name" => "ファミリー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
	],
	"english_talk_lesson" => [
		"child" => [
			"attribute_value" => "child",
			"attribute_name" => "子供英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"daily" => [
			"attribute_value" => "daily",
			"attribute_name" => "日常英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"business" => [
			"attribute_value" => "business",
			"attribute_name" => "ビジネス英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"certification" => [
			"attribute_value" => "certification",
			"attribute_name" => "資格検定・進学対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"chinese" => [
			"attribute_value" => "chinese",
			"attribute_name" => "中国語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"english_teacher" => [
		"japanese" => [
			"attribute_value" => "japanese",
			"attribute_name" => "日本人講師",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"foreigner" => [
			"attribute_value" => "foreigner",
			"attribute_name" => "外国人講師",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"both" => [
			"attribute_value" => "both",
			"attribute_name" => "どちらでも可",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
	],
	"entry_milestone" => [
		"entrance_examination" => [
			"attribute_value" => "entrance_examination",
			"attribute_name" => "受験対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"promotion" => [
			"attribute_value" => "promotion",
			"attribute_name" => "内部進学対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"training" => [
			"attribute_value" => "training",
			"attribute_name" => "宿題のフォロー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"examination" => [
			"attribute_value" => "examination",
			"attribute_name" => "定期試験に向けた予習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"eiken" => [
			"attribute_value" => "eiken",
			"attribute_name" => "英検対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"other" => [
			"attribute_value" => "other",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
	],
	"faq_type" => [
		"control" => [
			"attribute_value" => "control",
			"attribute_name" => "操作に関すること",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"schedule" => [
			"attribute_value" => "schedule",
			"attribute_name" => "授業予定に関すること",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"teacher" => [
			"attribute_value" => "teacher",
			"attribute_name" => "講師の方の操作について",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"manager" => [
			"attribute_value" => "manager",
			"attribute_name" => "事務の方の操作について",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"account" => [
			"attribute_value" => "account",
			"attribute_name" => "休会・退会について",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"grade" => [
		"k1" => [
			"attribute_value" => "k1",
			"attribute_name" => "年小",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"k2" => [
			"attribute_value" => "k2",
			"attribute_name" => "年中",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"k3" => [
			"attribute_value" => "k3",
			"attribute_name" => "年長",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"e1" => [
			"attribute_value" => "e1",
			"attribute_name" => "小1",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"e2" => [
			"attribute_value" => "e2",
			"attribute_name" => "小2",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"e3" => [
			"attribute_value" => "e3",
			"attribute_name" => "小3",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"e4" => [
			"attribute_value" => "e4",
			"attribute_name" => "小4",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"e5" => [
			"attribute_value" => "e5",
			"attribute_name" => "小5",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"e6" => [
			"attribute_value" => "e6",
			"attribute_name" => "小6",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"j1" => [
			"attribute_value" => "j1",
			"attribute_name" => "中1",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"j2" => [
			"attribute_value" => "j2",
			"attribute_name" => "中2",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"j3" => [
			"attribute_value" => "j3",
			"attribute_name" => "中3",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"h1" => [
			"attribute_value" => "h1",
			"attribute_name" => "高1",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"h2" => [
			"attribute_value" => "h2",
			"attribute_name" => "高2",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
		"h3" => [
			"attribute_value" => "h3",
			"attribute_name" => "高3",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "15",
		],
		"university" => [
			"attribute_value" => "university",
			"attribute_name" => "大学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "16",
		],
		"adult" => [
			"attribute_value" => "adult",
			"attribute_name" => "成人",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "17",
		],
	],
	"grade_adj" => [
		"-1" => [
			"attribute_value" => "-1",
			"attribute_name" => "-1",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"2" => [
			"attribute_value" => "2",
			"attribute_name" => "2",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
	],
	"howto" => [
		"google" => [
			"attribute_value" => "google",
			"attribute_name" => "Google検索",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"yahoo" => [
			"attribute_value" => "yahoo",
			"attribute_name" => "Yahoo検索",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"facebook" => [
			"attribute_value" => "facebook",
			"attribute_name" => "Facebook",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"instagram" => [
			"attribute_value" => "instagram",
			"attribute_name" => "Instagram",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"signboard" => [
			"attribute_value" => "signboard",
			"attribute_name" => "看板",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"newspaper" => [
			"attribute_value" => "newspaper",
			"attribute_name" => "新聞折込チラシ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"flyer" => [
			"attribute_value" => "flyer",
			"attribute_name" => "投函チラシ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"dm" => [
			"attribute_value" => "dm",
			"attribute_name" => "ダイレクトメール",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"introduce" => [
			"attribute_value" => "introduce",
			"attribute_name" => "生徒からの紹介",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
	],
	"importance" => [
		"0" => [
			"attribute_value" => "0",
			"attribute_name" => "低",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"5" => [
			"attribute_value" => "5",
			"attribute_name" => "中",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"7" => [
			"attribute_value" => "7",
			"attribute_name" => "中高",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"10" => [
			"attribute_value" => "10",
			"attribute_name" => "高",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
	],
	"keys" => [
		"keys" => [
			"attribute_value" => "keys",
			"attribute_name" => "定義項目",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"schedule_method" => [
			"attribute_value" => "schedule_method",
			"attribute_name" => "定期カレンダー反映方法",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"lesson" => [
			"attribute_value" => "lesson",
			"attribute_name" => "レッスン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"english_talk_lesson" => [
			"attribute_value" => "english_talk_lesson",
			"attribute_name" => "英会話レッスン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"kids_lesson" => [
			"attribute_value" => "kids_lesson",
			"attribute_name" => "習い事",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"course_minutes" => [
			"attribute_value" => "course_minutes",
			"attribute_name" => "授業時間",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"course_type" => [
			"attribute_value" => "course_type",
			"attribute_name" => "授業形式",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"teaching_type" => [
			"attribute_value" => "teaching_type",
			"attribute_name" => "授業タイプ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"charge_grade" => [
			"attribute_value" => "charge_grade",
			"attribute_name" => "担当学年",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"charge_subject" => [
			"attribute_value" => "charge_subject",
			"attribute_name" => "担当科目",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"charge_subject_level" => [
			"attribute_value" => "charge_subject_level",
			"attribute_name" => "担当科目Lv",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"course" => [
			"attribute_value" => "course",
			"attribute_name" => "コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"grade" => [
			"attribute_value" => "grade",
			"attribute_name" => "学年",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"level" => [
			"attribute_value" => "level",
			"attribute_name" => "難易度",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
		"absence_type" => [
			"attribute_value" => "absence_type",
			"attribute_name" => "休み種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "15",
		],
		"grade_adj" => [
			"attribute_value" => "grade_adj",
			"attribute_name" => "学年調整値(留年など)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "16",
		],
		"student_type" => [
			"attribute_value" => "student_type",
			"attribute_name" => "生徒種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "17",
		],
		"comment_type" => [
			"attribute_value" => "comment_type",
			"attribute_name" => "コメント種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "18",
		],
		"announcement_type" => [
			"attribute_value" => "announcement_type",
			"attribute_name" => "おしらせ種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "19",
		],
		"milestone_type" => [
			"attribute_value" => "milestone_type",
			"attribute_name" => "目標種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "20",
		],
		"importance" => [
			"attribute_value" => "importance",
			"attribute_name" => "重要度",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "21",
		],
		"howto" => [
			"attribute_value" => "howto",
			"attribute_name" => "当塾をお知りになった方法は何でしょうか",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "22",
		],
		"lesson_subject" => [
			"attribute_value" => "lesson_subject",
			"attribute_name" => "レッスン希望科目",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "23",
		],
		"lesson_subject_level" => [
			"attribute_value" => "lesson_subject_level",
			"attribute_name" => "科目希望対応",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "24",
		],
		"lesson_week" => [
			"attribute_value" => "lesson_week",
			"attribute_name" => "レッスン可能曜日",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "25",
		],
		"lesson_time" => [
			"attribute_value" => "lesson_time",
			"attribute_name" => "レッスン可能時間",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "26",
		],
		"work_time" => [
			"attribute_value" => "work_time",
			"attribute_name" => "勤務可能時間",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "27",
		],
		"english_teacher" => [
			"attribute_value" => "english_teacher",
			"attribute_name" => "英会話講師希望",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "28",
		],
		"piano_level" => [
			"attribute_value" => "piano_level",
			"attribute_name" => "ピアノ経験",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "29",
		],
		"matching_decide" => [
			"attribute_value" => "matching_decide",
			"attribute_name" => "マッチング決定理由",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "30",
		],
		"teacher_character" => [
			"attribute_value" => "teacher_character",
			"attribute_name" => "講師特性",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "31",
		],
		"manager_type" => [
			"attribute_value" => "manager_type",
			"attribute_name" => "事務種別",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "32",
		],
		"faq_type" => [
			"attribute_value" => "faq_type",
			"attribute_name" => "FAQ種類",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "33",
		],
		"bank_account_type" => [
			"attribute_value" => "bank_account_type",
			"attribute_name" => "口座種類",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "34",
		],
		"calendar_status" => [
			"attribute_value" => "calendar_status",
			"attribute_name" => "calendar_status",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "35",
		],
		"setting_status" => [
			"attribute_value" => "setting_status",
			"attribute_name" => "setting_status",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "36",
		],
		"entry_milestone" => [
			"attribute_value" => "entry_milestone",
			"attribute_name" => "特に重視してやって欲しいことをお知らせください",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "37",
		],
	],
	"kids_lesson" => [
		"programming" => [
			"attribute_value" => "programming",
			"attribute_name" => "プログラミング",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"abacus" => [
			"attribute_value" => "abacus",
			"attribute_name" => "そろばん",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"dance" => [
			"attribute_value" => "dance",
			"attribute_name" => "ダンス",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"science" => [
			"attribute_value" => "science",
			"attribute_name" => "サイエンスクラブ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"after_school" => [
			"attribute_value" => "after_school",
			"attribute_name" => "学童保育",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"japanese_school" => [
			"attribute_value" => "japanese_school",
			"attribute_name" => "国語教室",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"infant_lesson" => [
			"attribute_value" => "infant_lesson",
			"attribute_name" => "幼児教室",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
	],
	"lesson" => [
		"1" => [
			"attribute_value" => "1",
			"attribute_name" => "塾",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"2" => [
			"attribute_value" => "2",
			"attribute_name" => "英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"3" => [
			"attribute_value" => "3",
			"attribute_name" => "ピアノ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"4" => [
			"attribute_value" => "4",
			"attribute_name" => "習い事",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
	],
	"lesson_fri_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "45",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "46",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "47",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "48",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "49",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "50",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "51",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "52",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "53",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "54",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "fri",
			"sort_no" => "55",
		],
	],
	"lesson_mon_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "1",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "2",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "3",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "4",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "5",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "6",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "7",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "8",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "9",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "10",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "mon",
			"sort_no" => "11",
		],
	],
	"lesson_sat_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "56",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "57",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "58",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "59",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "60",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "61",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "62",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "63",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "64",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "65",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sat",
			"sort_no" => "66",
		],
	],
	"lesson_subject" => [
		"japanese" => [
			"attribute_value" => "japanese",
			"attribute_name" => "国語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"math" => [
			"attribute_value" => "math",
			"attribute_name" => "算数・数学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"english" => [
			"attribute_value" => "english",
			"attribute_name" => "英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"science" => [
			"attribute_value" => "science",
			"attribute_name" => "理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"society" => [
			"attribute_value" => "society",
			"attribute_name" => "社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"lesson_subject_level" => [
		"1" => [
			"attribute_value" => "1",
			"attribute_name" => "希望しない",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"10" => [
			"attribute_value" => "10",
			"attribute_name" => "補習授業",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"20" => [
			"attribute_value" => "20",
			"attribute_name" => "受験対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
	],
	"lesson_sun_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "67",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "68",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "69",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "70",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "71",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "72",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "73",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "74",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "75",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "76",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "sun",
			"sort_no" => "77",
		],
	],
	"lesson_thi_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "34",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "35",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "36",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "37",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "38",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "39",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "40",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "41",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "42",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "43",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "thi",
			"sort_no" => "44",
		],
	],
	"lesson_time" => [
		"08_09" => [
			"attribute_value" => "08_09",
			"attribute_name" => "8:00～9:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"09_10" => [
			"attribute_value" => "09_10",
			"attribute_name" => "9:00～10:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"10_11" => [
			"attribute_value" => "10_11",
			"attribute_name" => "10:00～11:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"11_12" => [
			"attribute_value" => "11_12",
			"attribute_name" => "11:00～12:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
	],
	"lesson_tue_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "12",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "13",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "14",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "15",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "16",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "17",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "18",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "19",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "20",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "21",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "tue",
			"sort_no" => "22",
		],
	],
	"lesson_wed_time" => [
		"am" => [
			"attribute_value" => "am",
			"attribute_name" => "午前中",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "23",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "24",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "25",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "26",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "27",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "28",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "29",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "30",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "31",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "32",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "lesson_week",
			"parent_attribute_value" => "wed",
			"sort_no" => "33",
		],
	],
	"lesson_week" => [
		"mon" => [
			"attribute_value" => "mon",
			"attribute_name" => "月",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"tue" => [
			"attribute_value" => "tue",
			"attribute_name" => "火",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"wed" => [
			"attribute_value" => "wed",
			"attribute_name" => "水",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"thi" => [
			"attribute_value" => "thi",
			"attribute_name" => "木",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"fri" => [
			"attribute_value" => "fri",
			"attribute_name" => "金",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"sat" => [
			"attribute_value" => "sat",
			"attribute_name" => "土",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"sun" => [
			"attribute_value" => "sun",
			"attribute_name" => "日",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
	],
	"manager_type" => [
		"admin" => [
			"attribute_value" => "admin",
			"attribute_name" => "管理者権限",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
	],
	"matching_decide" => [
		"subject" => [
			"attribute_value" => "subject",
			"attribute_name" => "担当科目が希望科目と一致した",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"schedule" => [
			"attribute_value" => "schedule",
			"attribute_name" => "体験授業予定に空きがあった",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"character" => [
			"attribute_value" => "character",
			"attribute_name" => "講師の性格を重視した",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"other" => [
			"attribute_value" => "other",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
	],
	"milestone_type" => [
		"entrance_examination" => [
			"attribute_value" => "entrance_examination",
			"attribute_name" => "入試",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"examination" => [
			"attribute_value" => "examination",
			"attribute_name" => "定期テスト",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"promotion" => [
			"attribute_value" => "promotion",
			"attribute_name" => "内部進学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"qualification" => [
			"attribute_value" => "qualification",
			"attribute_name" => "資格",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"other" => [
			"attribute_value" => "other",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"piano_level" => [
		"new" => [
			"attribute_value" => "new",
			"attribute_name" => "初心者",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"experienced" => [
			"attribute_value" => "experienced",
			"attribute_name" => "経験者",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
	],
	"schedule_method" => [
		"week" => [
			"attribute_value" => "week",
			"attribute_name" => "毎週",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"month" => [
			"attribute_value" => "month",
			"attribute_name" => "毎月",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
	],
	"season_school_lesson_milestone" => [
		"entrance_examination" => [
			"attribute_value" => "entrance_examination",
			"attribute_name" => "受験対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"promotion" => [
			"attribute_value" => "promotion",
			"attribute_name" => "内部進学対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"qualification" => [
			"attribute_value" => "qualification",
			"attribute_name" => "資格試験対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"training" => [
			"attribute_value" => "training",
			"attribute_name" => "補習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"other" => [
			"attribute_value" => "other",
			"attribute_name" => "その他",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
	],
	"setting_status" => [
		"dummy" => [
			"attribute_value" => "dummy",
			"attribute_name" => "ダミー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"new" => [
			"attribute_value" => "new",
			"attribute_name" => "予定(下書き)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"confirm" => [
			"attribute_value" => "confirm",
			"attribute_name" => "予定確認中",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"fix" => [
			"attribute_value" => "fix",
			"attribute_name" => "予定確定",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"cancel" => [
			"attribute_value" => "cancel",
			"attribute_name" => "キャンセル",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"closed" => [
			"attribute_value" => "closed",
			"attribute_name" => "終了",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
	],
	"student_character" => [
		"nervous" => [
			"attribute_value" => "nervous",
			"attribute_name" => "神経質",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"daring" => [
			"attribute_value" => "daring",
			"attribute_name" => "すぶとい",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"sociably" => [
			"attribute_value" => "sociably",
			"attribute_name" => "社交的",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"introvert" => [
			"attribute_value" => "introvert",
			"attribute_name" => "人見知り",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"quiet" => [
			"attribute_value" => "quiet",
			"attribute_name" => "おとなしい",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"active" => [
			"attribute_value" => "active",
			"attribute_name" => "活発的",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"honest" => [
			"attribute_value" => "honest",
			"attribute_name" => "素直",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"resist" => [
			"attribute_value" => "resist",
			"attribute_name" => "反発",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"serious" => [
			"attribute_value" => "serious",
			"attribute_name" => "真面目",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"laze" => [
			"attribute_value" => "laze",
			"attribute_name" => "不真面目",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"self-study" => [
			"attribute_value" => "self-study",
			"attribute_name" => "自立学習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"stern-parent" => [
			"attribute_value" => "stern-parent",
			"attribute_name" => "親が厳しい",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"intelligent" => [
			"attribute_value" => "intelligent",
			"attribute_name" => "自頭良い",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"good-submit" => [
			"attribute_value" => "good-submit",
			"attribute_name" => "提出物〇",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
		"bad-submit" => [
			"attribute_value" => "bad-submit",
			"attribute_name" => "提出物×",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "15",
		],
		"good-motivation" => [
			"attribute_value" => "good-motivation",
			"attribute_name" => "やる気〇",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "16",
		],
		"bad-motivation" => [
			"attribute_value" => "bad-motivation",
			"attribute_name" => "やる気×",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "17",
		],
		"delay-study" => [
			"attribute_value" => "delay-study",
			"attribute_name" => "学習遅れ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "18",
		],
		"difficult-school" => [
			"attribute_value" => "difficult-school",
			"attribute_name" => "難関志望",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "19",
		],
		"talking" => [
			"attribute_value" => "talking",
			"attribute_name" => "雑談好き",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "20",
		],
	],
	"student_type" => [
		"fee_free" => [
			"attribute_value" => "fee_free",
			"attribute_name" => "受講料無料",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"yuge_price" => [
			"attribute_value" => "yuge_price",
			"attribute_name" => "弓削先生が担当する場合、受講料+1000円",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"arrowre" => [
			"attribute_value" => "arrowre",
			"attribute_name" => "アローレ所属",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"internal_study" => [
			"attribute_value" => "internal_study",
			"attribute_name" => "内部進学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"juken" => [
			"attribute_value" => "juken",
			"attribute_name" => "受験",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"j_juken" => [
			"attribute_value" => "j_juken",
			"attribute_name" => "中学受験",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"restcare_holiday_is_a1" => [
			"attribute_value" => "restcare_holiday_is_a1",
			"attribute_name" => "休み判定用項目：祝日は休み1",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"restcare_first_rest_is_a1" => [
			"attribute_value" => "restcare_first_rest_is_a1",
			"attribute_name" => "休み判定用項目：初回の休みは休み１",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"restcare_rest_is_a1" => [
			"attribute_value" => "restcare_rest_is_a1",
			"attribute_name" => "休み判定用項目：常に休み１",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"restcare_rest_add_exchange_enable" => [
			"attribute_value" => "restcare_rest_add_exchange_enable",
			"attribute_name" => "休み判定用項目：常に振替対象",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"repeat_schedule_no_week5" => [
			"attribute_value" => "repeat_schedule_no_week5",
			"attribute_name" => "5週目の通常授業なし",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
	],
	"subject" => [
		"0" => [
			"attribute_value" => "0",
			"attribute_name" => "科目なし",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"1" => [
			"attribute_value" => "1",
			"attribute_name" => "数学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"2" => [
			"attribute_value" => "2",
			"attribute_name" => "理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"3" => [
			"attribute_value" => "3",
			"attribute_name" => "英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"4" => [
			"attribute_value" => "4",
			"attribute_name" => "算数",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"5" => [
			"attribute_value" => "5",
			"attribute_name" => "そろばん",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"6" => [
			"attribute_value" => "6",
			"attribute_name" => "国語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"7" => [
			"attribute_value" => "7",
			"attribute_name" => "旧面談",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"8" => [
			"attribute_value" => "8",
			"attribute_name" => "未定",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"9" => [
			"attribute_value" => "9",
			"attribute_name" => "化学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"10" => [
			"attribute_value" => "10",
			"attribute_name" => "社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"11" => [
			"attribute_value" => "11",
			"attribute_name" => "国語・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"12" => [
			"attribute_value" => "12",
			"attribute_name" => "国語・算数",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"13" => [
			"attribute_value" => "13",
			"attribute_name" => "数学・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"15" => [
			"attribute_value" => "15",
			"attribute_name" => "生物",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"16" => [
			"attribute_value" => "16",
			"attribute_name" => "理科・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"17" => [
			"attribute_value" => "17",
			"attribute_name" => "ギター",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"18" => [
			"attribute_value" => "18",
			"attribute_name" => "ピアノ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"19" => [
			"attribute_value" => "19",
			"attribute_name" => "国語・理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"20" => [
			"attribute_value" => "20",
			"attribute_name" => "理科・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"23" => [
			"attribute_value" => "23",
			"attribute_name" => "英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"24" => [
			"attribute_value" => "24",
			"attribute_name" => "古文",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"26" => [
			"attribute_value" => "26",
			"attribute_name" => "数学・理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"27" => [
			"attribute_value" => "27",
			"attribute_name" => "社会・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"28" => [
			"attribute_value" => "28",
			"attribute_name" => "物理",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"29" => [
			"attribute_value" => "29",
			"attribute_name" => "プログラミング",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"30" => [
			"attribute_value" => "30",
			"attribute_name" => "算数・理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"31" => [
			"attribute_value" => "31",
			"attribute_name" => "受験対策",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"32" => [
			"attribute_value" => "32",
			"attribute_name" => "英語・化学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"33" => [
			"attribute_value" => "33",
			"attribute_name" => "数学・物理",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"34" => [
			"attribute_value" => "34",
			"attribute_name" => "南多摩コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"35" => [
			"attribute_value" => "35",
			"attribute_name" => "私立受験コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"36" => [
			"attribute_value" => "36",
			"attribute_name" => "南多摩コース(グループ)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"37" => [
			"attribute_value" => "37",
			"attribute_name" => "算数・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"39" => [
			"attribute_value" => "39",
			"attribute_name" => "英語・生物・小論文",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"40" => [
			"attribute_value" => "40",
			"attribute_name" => "南多摩コース適性Ⅱ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"41" => [
			"attribute_value" => "41",
			"attribute_name" => "南多摩コース適性Ⅰ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"42" => [
			"attribute_value" => "42",
			"attribute_name" => "算数・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"43" => [
			"attribute_value" => "43",
			"attribute_name" => "中国語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"44" => [
			"attribute_value" => "44",
			"attribute_name" => "小論文",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"45" => [
			"attribute_value" => "45",
			"attribute_name" => "現代文",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"46" => [
			"attribute_value" => "46",
			"attribute_name" => "中２都立入試コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"47" => [
			"attribute_value" => "47",
			"attribute_name" => "数学・算数",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"48" => [
			"attribute_value" => "48",
			"attribute_name" => "中３都立入試コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"49" => [
			"attribute_value" => "49",
			"attribute_name" => "ダンス",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"50" => [
			"attribute_value" => "50",
			"attribute_name" => "国語教室",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"51" => [
			"attribute_value" => "51",
			"attribute_name" => "算数教室",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"52" => [
			"attribute_value" => "52",
			"attribute_name" => "国語・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"53" => [
			"attribute_value" => "53",
			"attribute_name" => "都立入試コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"54" => [
			"attribute_value" => "54",
			"attribute_name" => "適正検査II",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"55" => [
			"attribute_value" => "55",
			"attribute_name" => "幼児教室",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"56" => [
			"attribute_value" => "56",
			"attribute_name" => "適性検査Ⅱ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"57" => [
			"attribute_value" => "57",
			"attribute_name" => "南多摩コース適性検査I",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"58" => [
			"attribute_value" => "58",
			"attribute_name" => "世界史",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"59" => [
			"attribute_value" => "59",
			"attribute_name" => "作文",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"60" => [
			"attribute_value" => "60",
			"attribute_name" => "政治経済",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"61" => [
			"attribute_value" => "61",
			"attribute_name" => "国語・英語・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
	],
	"subject_expr" => [
		"ダンス" => [
			"attribute_value" => "ダンス",
			"attribute_name" => "ダンス",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"都立入試コース" => [
			"attribute_value" => "都立入試コース",
			"attribute_name" => "都立入試コース",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"英語" => [
			"attribute_value" => "英語",
			"attribute_name" => "英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"そろばん" => [
			"attribute_value" => "そろばん",
			"attribute_name" => "そろばん",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"算数・理科" => [
			"attribute_value" => "算数・理科",
			"attribute_name" => "算数・理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"数学・理科" => [
			"attribute_value" => "数学・理科",
			"attribute_name" => "数学・理科",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"数学・英語" => [
			"attribute_value" => "数学・英語",
			"attribute_name" => "数学・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"数学" => [
			"attribute_value" => "数学",
			"attribute_name" => "数学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"国語" => [
			"attribute_value" => "国語",
			"attribute_name" => "国語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"政治経済" => [
			"attribute_value" => "政治経済",
			"attribute_name" => "政治経済",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"国語・社会" => [
			"attribute_value" => "国語・社会",
			"attribute_name" => "国語・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"国語・算数" => [
			"attribute_value" => "国語・算数",
			"attribute_name" => "国語・算数",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"算数・英語" => [
			"attribute_value" => "算数・英語",
			"attribute_name" => "算数・英語",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"国語・英語・社会" => [
			"attribute_value" => "国語・英語・社会",
			"attribute_name" => "国語・英語・社会",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"英会話" => [
			"attribute_value" => "英会話",
			"attribute_name" => "英会話",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"算数" => [
			"attribute_value" => "算数",
			"attribute_name" => "算数",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"化学" => [
			"attribute_value" => "化学",
			"attribute_name" => "化学",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"ピアノ" => [
			"attribute_value" => "ピアノ",
			"attribute_name" => "ピアノ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
	],
	"teacher_character" => [
		"chief" => [
			"attribute_value" => "chief",
			"attribute_name" => "主任",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"public-school" => [
			"attribute_value" => "public-school",
			"attribute_name" => "都立公立",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"private-school" => [
			"attribute_value" => "private-school",
			"attribute_name" => "私立一貫",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"difficult-school" => [
			"attribute_value" => "difficult-school",
			"attribute_name" => "難関校",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"delay-class" => [
			"attribute_value" => "delay-class",
			"attribute_name" => "進度遅い",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"fast-class" => [
			"attribute_value" => "fast-class",
			"attribute_name" => "進度早い",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"class-first" => [
			"attribute_value" => "class-first",
			"attribute_name" => "授業中心",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"exercise-first" => [
			"attribute_value" => "exercise-first",
			"attribute_name" => "演習中心",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"leadership" => [
			"attribute_value" => "leadership",
			"attribute_name" => "リーダーシップ",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"balance" => [
			"attribute_value" => "balance",
			"attribute_name" => "生徒に柔軟",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"cool" => [
			"attribute_value" => "cool",
			"attribute_name" => "冷静",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"freiendly" => [
			"attribute_value" => "freiendly",
			"attribute_name" => "やさしい",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"strict" => [
			"attribute_value" => "strict",
			"attribute_name" => "厳しい",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"talking" => [
			"attribute_value" => "talking",
			"attribute_name" => "雑談好き",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
	],
	"teaching_type" => [
		"regular" => [
			"attribute_value" => "regular",
			"attribute_name" => "通常授業",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"trial" => [
			"attribute_value" => "trial",
			"attribute_name" => "体験授業",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"exchange" => [
			"attribute_value" => "exchange",
			"attribute_name" => "振替授業",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"add" => [
			"attribute_value" => "add",
			"attribute_name" => "追加授業",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"season" => [
			"attribute_value" => "season",
			"attribute_name" => "期間講習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"training" => [
			"attribute_value" => "training",
			"attribute_name" => "演習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"season_training" => [
			"attribute_value" => "season_training",
			"attribute_name" => "演習(期間講習)",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
	],
	"work" => [
		"3" => [
			"attribute_value" => "3",
			"attribute_name" => "面談",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"4" => [
			"attribute_value" => "4",
			"attribute_name" => "試験監督",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"5" => [
			"attribute_value" => "5",
			"attribute_name" => "演習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"6" => [
			"attribute_value" => "6",
			"attribute_name" => "マンツーマン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"7" => [
			"attribute_value" => "7",
			"attribute_name" => "グループレッスン",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"8" => [
			"attribute_value" => "8",
			"attribute_name" => "ファミリー",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"9" => [
			"attribute_value" => "9",
			"attribute_name" => "事務",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"10" => [
			"attribute_value" => "10",
			"attribute_name" => "季節および土日講習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"11" => [
			"attribute_value" => "11",
			"attribute_name" => "季節および土日講習演習",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
	],
	"work_time" => [
		"08_09" => [
			"attribute_value" => "08_09",
			"attribute_name" => "08:00～09:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "1",
		],
		"09_10" => [
			"attribute_value" => "09_10",
			"attribute_name" => "09:00～10:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "2",
		],
		"10_11" => [
			"attribute_value" => "10_11",
			"attribute_name" => "10:00～11:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "3",
		],
		"11_12" => [
			"attribute_value" => "11_12",
			"attribute_name" => "11:00～12:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "4",
		],
		"12_13" => [
			"attribute_value" => "12_13",
			"attribute_name" => "12:00～13:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "5",
		],
		"13_14" => [
			"attribute_value" => "13_14",
			"attribute_name" => "13:00～14:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "6",
		],
		"14_15" => [
			"attribute_value" => "14_15",
			"attribute_name" => "14:00～15:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "7",
		],
		"15_16" => [
			"attribute_value" => "15_16",
			"attribute_name" => "15:00～16:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "8",
		],
		"16_17" => [
			"attribute_value" => "16_17",
			"attribute_name" => "16:00～17:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "9",
		],
		"17_18" => [
			"attribute_value" => "17_18",
			"attribute_name" => "17:00～18:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "10",
		],
		"18_19" => [
			"attribute_value" => "18_19",
			"attribute_name" => "18:00～19:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "11",
		],
		"19_20" => [
			"attribute_value" => "19_20",
			"attribute_name" => "19:00～20:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "12",
		],
		"20_21" => [
			"attribute_value" => "20_21",
			"attribute_name" => "20:00～21:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "13",
		],
		"21_22" => [
			"attribute_value" => "21_22",
			"attribute_name" => "21:00～22:00",
			"parent_attribute_key" => "",
			"parent_attribute_value" => "",
			"sort_no" => "14",
		],
],); ?>