<?php
return array(
  'rest' => 'secondary',
  'rest_cancel' => 'warning',
  'lecture_cancel' => 'secondary',
  'absence' => 'danger',
  'confirm' => 'warning',
  'fix' => 'primary',
  'commit' => 'success',
  'presence' => 'success',
  'new' => 'secondary',
  'cancel' => 'secondary',
  'complete' => 'success',
  'trial' => 'warning',
  'regular' => 'success',
  'recess' => 'secondary',
  'unsubscribe' => 'secondary',
  'disabled' => 'secondary',
  'enabled' => 'success',
  'closed' => 'secondary',
  'entry_contact' => 'secondary',
  'entry_cancel' => 'secondary',
  'entry_hope' => 'primary',
  'entry_guidanced' => 'primary',
  'send' => 'warning',
  'error' => 'danger',
  'sended' => 'success',
  );
?>
